steps:
# Pull most recent Docker image.
- id: 'pull-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:bgogul']
  waitFor: ['-']

# Build the new Docker image (caching from the pre-built one)
- id: 'build-image'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:bgogul',
    '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:bgogul',
    '--tag=arcs-bgogul-base',
    '.',
  ]
  waitFor: ['pull-image']

# Push updated Docker image to Container Registry.
- id: 'push-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:bgogul']
  waitFor: ['build-image']

- id: 'web-pack'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',  '--rm', 'arcs-bgogul-base',
    'tools/sigh', 'webpack'
  ]
  waitFor: ['build-image']

- id: 'bazel-tests'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',
    '--network=cloudbuild',
    '--rm', 'arcs-bgogul-base',
    'tools/bazelisk',
    '--bazelrc=tools/gcb.bazelrc',
    'test', '//java/...', '//javatests/...', '//src/...', '//particles/...'
  ]
  waitFor: ['web-pack']

- id: 'test-shells'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run', '--rm', 'arcs-bgogul-base',
    'tools/sigh', 'testShells'
  ]
  dir: 'usr/src/app'
  waitFor: ['bazel-tests']

- id: 'sigh-test'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run', '--rm', 'arcs-bgogul-base',
    'tools/sigh', 'test'
  ]
  waitFor: ['web-pack']

- id: 'lint'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'run', '--rm', 'arcs-bgogul-base',
    'tools/sigh', 'lint'
  ]
  waitFor: ['web-pack']

images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'

timeout: 3600s # 60 mins, just in case.
logsBucket: 'gs://arcs-github-gcb-logs'
options:
  machineType: 'N1_HIGHCPU_32'

substitutions:
  _IMAGE_NAME: arcs
